name: fcb_pay_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth_repository:
    path: packages/firebase_auth_repository
  firebase_realtimedb_repository:
    path: packages/firebase_realtimedb_repository
  form_inputs:
    path: packages/form_inputs
  hive_pin_repository:
    path: packages/hive_pin_repository
  hive_repository:
    path: packages/hive_repository

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  carousel_slider: ^4.2.1
  mobile_scanner: ^3.4.1
  meta: ^1.9.1
  formz: ^0.6.1
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  flutter_html: ^3.0.0-beta.2
  shimmer: ^3.0.0
  crypto: ^3.0.3
  intl: ^0.18.1
  google_fonts: ^6.1.0
  flow_builder: ^0.0.9
  url_launcher: ^6.1.14
  font_awesome_flutter: ^10.5.0
  firebase_auth_platform_interface: ^6.19.1
  hive_generator: ^2.0.1
  bloc_concurrency: ^0.2.2
  dio: ^5.3.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  plugin_platform_interface: ^2.1.6
  test: ^1.16.0
  bloc_test: ^9.1.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/fcb-logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fcb-logo.png
    - assets/bg.png
    - assets/login.svg
