name: fcb_pay_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth_repository:
    path: packages/firebase_auth_repository
  form_inputs:
    path: packages/form_inputs

  unicons: ^2.1.1
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  equatable: ^2.0.5
  firebase_core: ^2.8.0
  firebase_database: ^10.0.16
  firebase_auth: ^4.4.0
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  carousel_slider: ^4.2.1
  mobile_scanner: ^3.2.0
  meta: ^1.8.0
  formz: ^0.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  path_provider: ^2.0.14
  flutter_html: ^2.2.1
  shimmer: ^2.0.0
  crypto: ^3.0.2
  intl: ^0.17.0
  google_fonts: ^4.0.3
  flow_builder: ^0.0.9
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.2.1
  flutter_launcher_icons: ^0.11.0
  plugin_platform_interface: ^2.1.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/fcb-logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fcb-logo.png
    - assets/login.svg
    - assets/html5.png
    - assets/mac.svg
