name: fcb_pay_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth_repository:
    path: packages/firebase_auth_repository
  firebase_realtimedb_repository:
    path: packages/firebase_realtimedb_repository
  form_inputs:
    path: packages/form_inputs
  hive_pin_repository:
    path: packages/hive_pin_repository
  hive_repository:
    path: packages/hive_repository
  firebase_storage_repository:
    path: packages/firebase_storage_repository

  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  firebase_storage: ^12.0.0
  carousel_slider: ^4.2.1
  mobile_scanner: ^4.0.1
  meta: ^1.9.1
  formz: ^0.7.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  shimmer: ^3.0.0
  crypto: ^3.0.3
  intl: ^0.19.0
  flow_builder: ^0.1.0
  font_awesome_flutter: ^10.7.0
  hive_generator: ^2.0.1
  dio: ^5.4.3+1
  image_gallery_saver: ^2.0.3
  local_auth: ^2.2.0
  flex_color_scheme: ^7.3.1
  pinput: ^5.0.0
  flutter_svg: ^2.0.10+1
  introduction_screen: ^3.1.14
  flutter_spinkit: ^5.2.1
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.13.0
  flutter_easyloading: ^3.0.5
  hydrated_bloc: ^9.1.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.13.1
  plugin_platform_interface: ^2.1.8
  bloc_test: ^9.1.7
  firebase_auth_platform_interface: ^7.3.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/image/fcb-logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/image/fcb-logo.png
    - assets/image/splash.png
    - assets/image/bg.png
    - assets/image/profile-bg.png
    - assets/svg/login.svg
    - assets/svg/otp.svg
    - assets/svg/credit_card_payment.svg
    - assets/svg/credit_card_payments.svg
    - assets/svg/mobile_pay.svg
    - assets/svg/online_banking.svg
    - assets/svg/online_payments.svg
    - assets/svg/online_transactions.svg
    - assets/svg/payments.svg
    - assets/svg/profile_data.svg
    - assets/svg/transfer_money.svg
    
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          weight: 900