name: firebase_realtimedb_repository
description: Dart package which manage the firebase realtime database domain.
version: 1.0.0
publish_to: none

environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  equatable: ^2.0.5
  firebase_core: ^2.21.0
  firebase_database: ^10.3.3
  firebase_auth: ^4.12.1
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.1
  very_good_analysis: ^5.1.0
