name: firebase_realtimedb_repository
description: Dart package which manage the firebase realtime database domain.
version: 1.0.0
publish_to: none

environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  equatable: ^2.0.5
  firebase_core: ^2.17.1
  firebase_database: ^10.3.1
  firebase_auth: ^4.10.1
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1
