name: firebase_realtimedb_repository
description: Dart package which manage the firebase realtime database domain.
version: 1.0.0
publish_to: none

environment: 
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  equatable: ^2.0.5
  firebase_core: ^2.8.0
  firebase_database: ^10.1.0
  firebase_auth: ^4.4.0
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1
