enum AppStatus {
  splash,
  register,
  unauthenticated,
  authenticated,
  pin,
  createPin,
  account,
  accountDynamicViewer,
  accountDynamicViewerReciept,
  dynamicViewer,
  dynamicViewerReceipt,
  scannerTransaction,
  addAccount,
  scannerTransactionReceipt,
  notifications,
  notificationViewer,
}