// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvsMsGwLwUvD5qVxefBGSm6LG2QRsPswA',
    appId: '1:1032216805729:android:cc9a147b72111fb0214520',
    messagingSenderId: '1032216805729',
    projectId: 'fcbpay-website-7c029',
    databaseURL: 'https://fcbpay-website-7c029-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fcbpay-website-7c029.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAFLe6KCUG8wOYRkcxzohiAQL9_Pxe9S4',
    appId: '1:1032216805729:ios:59826b8f756f326c214520',
    messagingSenderId: '1032216805729',
    projectId: 'fcbpay-website-7c029',
    databaseURL: 'https://fcbpay-website-7c029-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fcbpay-website-7c029.appspot.com',
    androidClientId: '1032216805729-2o6cetbeqjece81s7jm92htvdm4bqui5.apps.googleusercontent.com',
    iosClientId: '1032216805729-clogajrulasg0jrgjo5rsg5sifsjhm6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcbPayApp',
  );
}
