name: firebase_storage_repository
description: "package for storage"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  firebase_auth: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_core: ^3.0.0
  image_picker: ^1.1.2
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
