name: firebase_auth_repository
description: Dart package which manages the firebase auth domain.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cache:
    path: ../cache

  equatable: ^2.0.5
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  google_sign_in: ^6.2.1
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  firebase_auth_platform_interface: ^7.3.1
  plugin_platform_interface: ^2.1.8