name: firebase_auth_repository
description: Dart package which manages the firebase auth domain.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cache:
    path: ../cache

  equatable: ^2.0.5
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  google_sign_in: ^6.1.4
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  firebase_auth_platform_interface: ^6.15.2
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.4
  very_good_analysis: ^5.0.0+1